mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 1 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 2 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 3 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 4 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 5 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 6 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 7 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 8 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 9 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 10 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 11 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 12 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 13 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 14 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 15 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 16 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 17 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 18 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 19 mpi-integral >> time.out;
sleep 1s;
mpicxx --std=c++11 -march=native -O3 mpi-integral.cpp -o mpi-integral; mpirun --oversubscribe -np 20 mpi-integral >> time.out;
sleep 1s;
